# github actions가 어느 시점에서 무엇을 어떻게 수행해야 하는지

name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: write env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Set up and build Docker Compose
        run: |
          ls -R
          sudo apt-get update
          sudo apt-get -y install docker-compose
          docker-compose build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id : login-ecr
        uses : aws-actions/amazon-ecr-login@v1

      - name : Build, tag, and push image to Amazon ECR
        run : |
            docker-compose push

      - name: Connect and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ubuntu
          key: ${{ secrets.PEM_KEY }}
          script: |
            docker ps
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            pwd
            ls
            cd /home/ubuntu/backend-deploy/
            git pull origin main
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335419749.dkr.ecr.us-east-1.amazonaws.com
            docker-compose pull  # Pull the latest images on EC2
            docker-compose up -d  # Run the containers on EC2